apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
  labels:
    version: v1
    app: employees
spec:
    type: NodePort
    ports:
    -   port: 8080
        targetPort: 8080
        nodePort: 30000
    selector:
        app: employees
        version: v1
