apiVersion: apps/v1
kind: ReplicaSet
metadata:
    labels:
        app: mysql
    name: mysql-db-rep
    namespace: sqldb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                -   image: 014677518946.dkr.ecr.us-east-1.amazonaws.com/web-db:latest
                    name: mysql-db
                    env:
                        - name: MYSQL_ROOT_PASSWORD
                          valueFrom:
                            secretKeyRef:
                                name: db-secrets
                                key: password
                    ports:
                        - containerPort: 3306
            dnsPolicy: ClusterFirst
            restartPolicy: Always
