apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp-v2
    namespace: webapp
    labels:
        app: employees
        version: v2
spec:
    replicas: 3
    selector:
        matchLabels:
            app: employees
            version: v2
    template:
        metadata:
            labels:
                app: employees
                version: v2
        spec:
            containers:
            -   name: webapp-v2
                image: 014677518946.dkr.ecr.us-east-1.amazonaws.com/web-app:v2
                env:
                    -   name: DBHOST
                        value: "10.244.0.5"
                    -   name: DBPORT
                        value: "3306"
                    -   name: DBPWD
                        valueFrom:
                            secretKeyRef:
                                name: db-secrets
                                key: password
                ports:
                    - containerPort: 8080
            dnsPolicy: ClusterFirst
            restartPolicy: Always
