apiVersion: v1
kind: Service
metadata:
  name: webapp-v2
  namespace: webapp
  labels:
    version: v2
    app: employees
spec:
    type: NodePort
    ports:
    -   port: 8080
        targetPort: 8080
        nodePort: 30001
    selector:
        app: employees
        version: v2
